In [20]:
import pandas as pd

In [4]:
df_uofl = pd.read_csv('../original-data/uofl.csv')

/var/folders/wd/wynvzl4x4sn834srpzwscw_m0000gn/T/ipykernel_99607/1132365206.py:1: DtypeWarning: Columns (0: last_updated_on, 1: location_name, 2: hospital_address, 3: type_2_npi, 4: license_number | KY, 5: attester_name, 6: To the best of its knowledge and belief, this hospital has included all applicable standard charge information in accordance with the requirements of 45 CFR 180.50, and the information encoded is true, accurate, and complete as of the date in the file. This hospital has included all payer-specific negotiated charges in dollars that can be expressed as a dollar amount. For payer-specific negotiated charges that cannot be expressed as a dollar amount in the machine-readable file or not knowable in advance, the hospital attests that the payer-specific negotiated charge is based on a contractual algorithm, percentage or formula that precludes the provision of a dollar amount and has provided all necessary information available to the hospital for the public to be able to derive the dollar amount, including, but not limited to, the specific fee schedule or components referenced in such percentage, algorithm or formula., 7: Unnamed: 11, 8: Unnamed: 12, 9: Unnamed: 13, 10: Unnamed: 14, 11: Unnamed: 15, 12: Unnamed: 16, 13: Unnamed: 17, 14: Unnamed: 18, 15: Unnamed: 19, 16: Unnamed: 20, 17: Unnamed: 21, 18: Unnamed: 22, 19: Unnamed: 23, 20: Unnamed: 24, 21: Unnamed: 25, 22: Unnamed: 26, 23: Unnamed: 27, 24: Unnamed: 28, 25: Unnamed: 29, 26: Unnamed: 30, 27: Unnamed: 31, 28: Unnamed: 32, 29: Unnamed: 33, 30: Unnamed: 34, 31: Unnamed: 35, 32: Unnamed: 36, 33: Unnamed: 37, 34: Unnamed: 38, 35: Unnamed: 39, 36: Unnamed: 40, 37: Unnamed: 41, 38: Unnamed: 42, 39: Unnamed: 43, 40: Unnamed: 45, 41: Unnamed: 46, 42: Unnamed: 47, 43: Unnamed: 48, 44: Unnamed: 49, 45: Unnamed: 50, 46: Unnamed: 51, 47: Unnamed: 52, 48: Unnamed: 53, 49: Unnamed: 54, 50: Unnamed: 55, 51: Unnamed: 56, 52: Unnamed: 57, 53: Unnamed: 58, 54: Unnamed: 59, 55: Unnamed: 60, 56: Unnamed: 61, 57: Unnamed: 63, 58: Unnamed: 64, 59: Unnamed: 65, 60: Unnamed: 66, 61: Unnamed: 67, 62: Unnamed: 68, 63: Unnamed: 69, 64: Unnamed: 70, 65: Unnamed: 72, 66: Unnamed: 73, 67: Unnamed: 74, 68: Unnamed: 75, 69: Unnamed: 76, 70: Unnamed: 77, 71: Unnamed: 78, 72: Unnamed: 79, 73: Unnamed: 80, 74: Unnamed: 81, 75: Unnamed: 82, 76: Unnamed: 83, 77: Unnamed: 84, 78: Unnamed: 85, 79: Unnamed: 86, 80: Unnamed: 87, 81: Unnamed: 88, 82: Unnamed: 89, 83: Unnamed: 90, 84: Unnamed: 91, 85: Unnamed: 92, 86: Unnamed: 93, 87: Unnamed: 94, 88: Unnamed: 95, 89: Unnamed: 96, 90: Unnamed: 97, 91: Unnamed: 98, 92: Unnamed: 99, 93: Unnamed: 100, 94: Unnamed: 101, 95: Unnamed: 102, 96: Unnamed: 103, 97: Unnamed: 104, 98: Unnamed: 105, 99: Unnamed: 106, 100: Unnamed: 107, 101: Unnamed: 108, 102: Unnamed: 109, 103: Unnamed: 110, 104: Unnamed: 111, 105: Unnamed: 112, 106: Unnamed: 113, 107: Unnamed: 114, 108: Unnamed: 115, 109: Unnamed: 117, 110: Unnamed: 118, 111: Unnamed: 119, 112: Unnamed: 120, 113: Unnamed: 121, 114: Unnamed: 122, 115: Unnamed: 123, 116: Unnamed: 124, 117: Unnamed: 125, 118: Unnamed: 126, 119: Unnamed: 127, 120: Unnamed: 128, 121: Unnamed: 129, 122: Unnamed: 130, 123: Unnamed: 131, 124: Unnamed: 132, 125: Unnamed: 133, 126: Unnamed: 134, 127: Unnamed: 135, 128: Unnamed: 136, 129: Unnamed: 137, 130: Unnamed: 138, 131: Unnamed: 139, 132: Unnamed: 140, 133: Unnamed: 141, 134: Unnamed: 142, 135: Unnamed: 143, 136: Unnamed: 144, 137: Unnamed: 145, 138: Unnamed: 146, 139: Unnamed: 147, 140: Unnamed: 148, 141: Unnamed: 149, 142: Unnamed: 150, 143: Unnamed: 151, 144: Unnamed: 152, 145: Unnamed: 153, 146: Unnamed: 154, 147: Unnamed: 155, 148: Unnamed: 156, 149: Unnamed: 157, 150: Unnamed: 158, 151: Unnamed: 159, 152: Unnamed: 160, 153: Unnamed: 161, 154: Unnamed: 162, 155: Unnamed: 163, 156: Unnamed: 164, 157: Unnamed: 165, 158: Unnamed: 166, 159: Unnamed: 167, 160: Unnamed: 168, 161: Unnamed: 169, 162: Unnamed: 170, 163: Unnamed: 171, 164: Unnamed: 172, 165: Unnamed: 173, 166: Unnamed: 174, 167: Unnamed: 175, 168: Unnamed: 176, 169: Unnamed: 177, 170: Unnamed: 178, 171: Unnamed: 179, 172: Unnamed: 180, 173: Unnamed: 181, 174: Unnamed: 182, 175: Unnamed: 183, 176: Unnamed: 184, 177: Unnamed: 185, 178: Unnamed: 186, 179: Unnamed: 187, 180: Unnamed: 188, 181: Unnamed: 189, 182: Unnamed: 190, 183: Unnamed: 191, 184: Unnamed: 192, 185: Unnamed: 193, 186: Unnamed: 194, 187: Unnamed: 195, 188: Unnamed: 196, 189: Unnamed: 197, 190: Unnamed: 198, 191: Unnamed: 199, 192: Unnamed: 200, 193: Unnamed: 201, 194: Unnamed: 202, 195: Unnamed: 203, 196: Unnamed: 204, 197: Unnamed: 205, 198: Unnamed: 206, 199: Unnamed: 207, 200: Unnamed: 208, 201: Unnamed: 209, 202: Unnamed: 210, 203: Unnamed: 211, 204: Unnamed: 212, 205: Unnamed: 213, 206: Unnamed: 214, 207: Unnamed: 215, 208: Unnamed: 216, 209: Unnamed: 217, 210: Unnamed: 218, 211: Unnamed: 219, 212: Unnamed: 220, 213: Unnamed: 221, 214: Unnamed: 222, 215: Unnamed: 223, 216: Unnamed: 224, 217: Unnamed: 225, 218: Unnamed: 226, 219: Unnamed: 227, 220: Unnamed: 228, 221: Unnamed: 229, 222: Unnamed: 230, 223: Unnamed: 231, 224: Unnamed: 232, 225: Unnamed: 234, 226: Unnamed: 235, 227: Unnamed: 236, 228: Unnamed: 237, 229: Unnamed: 238, 230: Unnamed: 239, 231: Unnamed: 240, 232: Unnamed: 241, 233: Unnamed: 243, 234: Unnamed: 244, 235: Unnamed: 245, 236: Unnamed: 246, 237: Unnamed: 247, 238: Unnamed: 248, 239: Unnamed: 249, 240: Unnamed: 250, 241: Unnamed: 251, 242: Unnamed: 252, 243: Unnamed: 253, 244: Unnamed: 254, 245: Unnamed: 255, 246: Unnamed: 256, 247: Unnamed: 257, 248: Unnamed: 258, 249: Unnamed: 259, 250: Unnamed: 260, 251: Unnamed: 261, 252: Unnamed: 262, 253: Unnamed: 263, 254: Unnamed: 264, 255: Unnamed: 265, 256: Unnamed: 266, 257: Unnamed: 267, 258: Unnamed: 268, 259: Unnamed: 269, 260: Unnamed: 270, 261: Unnamed: 271, 262: Unnamed: 272, 263: Unnamed: 273, 264: Unnamed: 274, 265: Unnamed: 275, 266: Unnamed: 276, 267: Unnamed: 277, 268: Unnamed: 278, 269: Unnamed: 279, 270: Unnamed: 280, 271: Unnamed: 281, 272: Unnamed: 282, 273: Unnamed: 283, 274: Unnamed: 284, 275: Unnamed: 285, 276: Unnamed: 286, 277: Unnamed: 287, 278: Unnamed: 288, 279: Unnamed: 289, 280: Unnamed: 290, 281: Unnamed: 291, 282: Unnamed: 292, 283: Unnamed: 293, 284: Unnamed: 294, 285: Unnamed: 295, 286: Unnamed: 297, 287: Unnamed: 298, 288: Unnamed: 299, 289: Unnamed: 300, 290: Unnamed: 301, 291: Unnamed: 302, 292: Unnamed: 303, 293: Unnamed: 304, 294: Unnamed: 305, 295: Unnamed: 306, 296: Unnamed: 307, 297: Unnamed: 308, 298: Unnamed: 309, 299: Unnamed: 310, 300: Unnamed: 311, 301: Unnamed: 312, 302: Unnamed: 313, 303: Unnamed: 314, 304: Unnamed: 315, 305: Unnamed: 316, 306: Unnamed: 317, 307: Unnamed: 318, 308: Unnamed: 319, 309: Unnamed: 320, 310: Unnamed: 321, 311: Unnamed: 322, 312: Unnamed: 323, 313: Unnamed: 324, 314: Unnamed: 325, 315: Unnamed: 326, 316: Unnamed: 327, 317: Unnamed: 328, 318: Unnamed: 329, 319: Unnamed: 330, 320: Unnamed: 331, 321: Unnamed: 332, 322: Unnamed: 333, 323: Unnamed: 334, 324: Unnamed: 335, 325: Unnamed: 336, 326: Unnamed: 337, 327: Unnamed: 338, 328: Unnamed: 339, 329: Unnamed: 340, 330: Unnamed: 341, 331: Unnamed: 342, 332: Unnamed: 343, 333: Unnamed: 344, 334: Unnamed: 345, 335: Unnamed: 346, 336: Unnamed: 347, 337: Unnamed: 348, 338: Unnamed: 349, 339: Unnamed: 350, 340: Unnamed: 351, 341: Unnamed: 352, 342: Unnamed: 353, 343: Unnamed: 354, 344: Unnamed: 355, 345: Unnamed: 356, 346: Unnamed: 357, 347: Unnamed: 358, 348: Unnamed: 359, 349: Unnamed: 360, 350: Unnamed: 361, 351: Unnamed: 362, 352: Unnamed: 363, 353: Unnamed: 364, 354: Unnamed: 365, 355: Unnamed: 366, 356: Unnamed: 367, 357: Unnamed: 368, 358: Unnamed: 369, 359: Unnamed: 370, 360: Unnamed: 371, 361: Unnamed: 372, 362: Unnamed: 373, 363: Unnamed: 374, 364: Unnamed: 375, 365: Unnamed: 376, 366: Unnamed: 377, 367: Unnamed: 378) have mixed types. Specify dtype option on import or set low_memory=False.
  df_uofl = pd.read_csv('../original-data/uofl.csv')

In [28]:
df_uofl.shape

(239368, 379)

In [10]:
df_uofl = pd.read_csv(
    "../original-data/uofl.csv"
)
df_uofl.head(100).to_csv('first_100_uofl.csv', index=False)

/var/folders/wd/wynvzl4x4sn834srpzwscw_m0000gn/T/ipykernel_99607/530571817.py:1: DtypeWarning: Columns (0: last_updated_on, 1: location_name, 2: hospital_address, 3: type_2_npi, 4: license_number | KY, 5: attester_name, 6: To the best of its knowledge and belief, this hospital has included all applicable standard charge information in accordance with the requirements of 45 CFR 180.50, and the information encoded is true, accurate, and complete as of the date in the file. This hospital has included all payer-specific negotiated charges in dollars that can be expressed as a dollar amount. For payer-specific negotiated charges that cannot be expressed as a dollar amount in the machine-readable file or not knowable in advance, the hospital attests that the payer-specific negotiated charge is based on a contractual algorithm, percentage or formula that precludes the provision of a dollar amount and has provided all necessary information available to the hospital for the public to be able to derive the dollar amount, including, but not limited to, the specific fee schedule or components referenced in such percentage, algorithm or formula., 7: Unnamed: 11, 8: Unnamed: 12, 9: Unnamed: 13, 10: Unnamed: 14, 11: Unnamed: 15, 12: Unnamed: 16, 13: Unnamed: 17, 14: Unnamed: 18, 15: Unnamed: 19, 16: Unnamed: 20, 17: Unnamed: 21, 18: Unnamed: 22, 19: Unnamed: 23, 20: Unnamed: 24, 21: Unnamed: 25, 22: Unnamed: 26, 23: Unnamed: 27, 24: Unnamed: 28, 25: Unnamed: 29, 26: Unnamed: 30, 27: Unnamed: 31, 28: Unnamed: 32, 29: Unnamed: 33, 30: Unnamed: 34, 31: Unnamed: 35, 32: Unnamed: 36, 33: Unnamed: 37, 34: Unnamed: 38, 35: Unnamed: 39, 36: Unnamed: 40, 37: Unnamed: 41, 38: Unnamed: 42, 39: Unnamed: 43, 40: Unnamed: 45, 41: Unnamed: 46, 42: Unnamed: 47, 43: Unnamed: 48, 44: Unnamed: 49, 45: Unnamed: 50, 46: Unnamed: 51, 47: Unnamed: 52, 48: Unnamed: 53, 49: Unnamed: 54, 50: Unnamed: 55, 51: Unnamed: 56, 52: Unnamed: 57, 53: Unnamed: 58, 54: Unnamed: 59, 55: Unnamed: 60, 56: Unnamed: 61, 57: Unnamed: 63, 58: Unnamed: 64, 59: Unnamed: 65, 60: Unnamed: 66, 61: Unnamed: 67, 62: Unnamed: 68, 63: Unnamed: 69, 64: Unnamed: 70, 65: Unnamed: 72, 66: Unnamed: 73, 67: Unnamed: 74, 68: Unnamed: 75, 69: Unnamed: 76, 70: Unnamed: 77, 71: Unnamed: 78, 72: Unnamed: 79, 73: Unnamed: 80, 74: Unnamed: 81, 75: Unnamed: 82, 76: Unnamed: 83, 77: Unnamed: 84, 78: Unnamed: 85, 79: Unnamed: 86, 80: Unnamed: 87, 81: Unnamed: 88, 82: Unnamed: 89, 83: Unnamed: 90, 84: Unnamed: 91, 85: Unnamed: 92, 86: Unnamed: 93, 87: Unnamed: 94, 88: Unnamed: 95, 89: Unnamed: 96, 90: Unnamed: 97, 91: Unnamed: 98, 92: Unnamed: 99, 93: Unnamed: 100, 94: Unnamed: 101, 95: Unnamed: 102, 96: Unnamed: 103, 97: Unnamed: 104, 98: Unnamed: 105, 99: Unnamed: 106, 100: Unnamed: 107, 101: Unnamed: 108, 102: Unnamed: 109, 103: Unnamed: 110, 104: Unnamed: 111, 105: Unnamed: 112, 106: Unnamed: 113, 107: Unnamed: 114, 108: Unnamed: 115, 109: Unnamed: 117, 110: Unnamed: 118, 111: Unnamed: 119, 112: Unnamed: 120, 113: Unnamed: 121, 114: Unnamed: 122, 115: Unnamed: 123, 116: Unnamed: 124, 117: Unnamed: 125, 118: Unnamed: 126, 119: Unnamed: 127, 120: Unnamed: 128, 121: Unnamed: 129, 122: Unnamed: 130, 123: Unnamed: 131, 124: Unnamed: 132, 125: Unnamed: 133, 126: Unnamed: 134, 127: Unnamed: 135, 128: Unnamed: 136, 129: Unnamed: 137, 130: Unnamed: 138, 131: Unnamed: 139, 132: Unnamed: 140, 133: Unnamed: 141, 134: Unnamed: 142, 135: Unnamed: 143, 136: Unnamed: 144, 137: Unnamed: 145, 138: Unnamed: 146, 139: Unnamed: 147, 140: Unnamed: 148, 141: Unnamed: 149, 142: Unnamed: 150, 143: Unnamed: 151, 144: Unnamed: 152, 145: Unnamed: 153, 146: Unnamed: 154, 147: Unnamed: 155, 148: Unnamed: 156, 149: Unnamed: 157, 150: Unnamed: 158, 151: Unnamed: 159, 152: Unnamed: 160, 153: Unnamed: 161, 154: Unnamed: 162, 155: Unnamed: 163, 156: Unnamed: 164, 157: Unnamed: 165, 158: Unnamed: 166, 159: Unnamed: 167, 160: Unnamed: 168, 161: Unnamed: 169, 162: Unnamed: 170, 163: Unnamed: 171, 164: Unnamed: 172, 165: Unnamed: 173, 166: Unnamed: 174, 167: Unnamed: 175, 168: Unnamed: 176, 169: Unnamed: 177, 170: Unnamed: 178, 171: Unnamed: 179, 172: Unnamed: 180, 173: Unnamed: 181, 174: Unnamed: 182, 175: Unnamed: 183, 176: Unnamed: 184, 177: Unnamed: 185, 178: Unnamed: 186, 179: Unnamed: 187, 180: Unnamed: 188, 181: Unnamed: 189, 182: Unnamed: 190, 183: Unnamed: 191, 184: Unnamed: 192, 185: Unnamed: 193, 186: Unnamed: 194, 187: Unnamed: 195, 188: Unnamed: 196, 189: Unnamed: 197, 190: Unnamed: 198, 191: Unnamed: 199, 192: Unnamed: 200, 193: Unnamed: 201, 194: Unnamed: 202, 195: Unnamed: 203, 196: Unnamed: 204, 197: Unnamed: 205, 198: Unnamed: 206, 199: Unnamed: 207, 200: Unnamed: 208, 201: Unnamed: 209, 202: Unnamed: 210, 203: Unnamed: 211, 204: Unnamed: 212, 205: Unnamed: 213, 206: Unnamed: 214, 207: Unnamed: 215, 208: Unnamed: 216, 209: Unnamed: 217, 210: Unnamed: 218, 211: Unnamed: 219, 212: Unnamed: 220, 213: Unnamed: 221, 214: Unnamed: 222, 215: Unnamed: 223, 216: Unnamed: 224, 217: Unnamed: 225, 218: Unnamed: 226, 219: Unnamed: 227, 220: Unnamed: 228, 221: Unnamed: 229, 222: Unnamed: 230, 223: Unnamed: 231, 224: Unnamed: 232, 225: Unnamed: 234, 226: Unnamed: 235, 227: Unnamed: 236, 228: Unnamed: 237, 229: Unnamed: 238, 230: Unnamed: 239, 231: Unnamed: 240, 232: Unnamed: 241, 233: Unnamed: 243, 234: Unnamed: 244, 235: Unnamed: 245, 236: Unnamed: 246, 237: Unnamed: 247, 238: Unnamed: 248, 239: Unnamed: 249, 240: Unnamed: 250, 241: Unnamed: 251, 242: Unnamed: 252, 243: Unnamed: 253, 244: Unnamed: 254, 245: Unnamed: 255, 246: Unnamed: 256, 247: Unnamed: 257, 248: Unnamed: 258, 249: Unnamed: 259, 250: Unnamed: 260, 251: Unnamed: 261, 252: Unnamed: 262, 253: Unnamed: 263, 254: Unnamed: 264, 255: Unnamed: 265, 256: Unnamed: 266, 257: Unnamed: 267, 258: Unnamed: 268, 259: Unnamed: 269, 260: Unnamed: 270, 261: Unnamed: 271, 262: Unnamed: 272, 263: Unnamed: 273, 264: Unnamed: 274, 265: Unnamed: 275, 266: Unnamed: 276, 267: Unnamed: 277, 268: Unnamed: 278, 269: Unnamed: 279, 270: Unnamed: 280, 271: Unnamed: 281, 272: Unnamed: 282, 273: Unnamed: 283, 274: Unnamed: 284, 275: Unnamed: 285, 276: Unnamed: 286, 277: Unnamed: 287, 278: Unnamed: 288, 279: Unnamed: 289, 280: Unnamed: 290, 281: Unnamed: 291, 282: Unnamed: 292, 283: Unnamed: 293, 284: Unnamed: 294, 285: Unnamed: 295, 286: Unnamed: 297, 287: Unnamed: 298, 288: Unnamed: 299, 289: Unnamed: 300, 290: Unnamed: 301, 291: Unnamed: 302, 292: Unnamed: 303, 293: Unnamed: 304, 294: Unnamed: 305, 295: Unnamed: 306, 296: Unnamed: 307, 297: Unnamed: 308, 298: Unnamed: 309, 299: Unnamed: 310, 300: Unnamed: 311, 301: Unnamed: 312, 302: Unnamed: 313, 303: Unnamed: 314, 304: Unnamed: 315, 305: Unnamed: 316, 306: Unnamed: 317, 307: Unnamed: 318, 308: Unnamed: 319, 309: Unnamed: 320, 310: Unnamed: 321, 311: Unnamed: 322, 312: Unnamed: 323, 313: Unnamed: 324, 314: Unnamed: 325, 315: Unnamed: 326, 316: Unnamed: 327, 317: Unnamed: 328, 318: Unnamed: 329, 319: Unnamed: 330, 320: Unnamed: 331, 321: Unnamed: 332, 322: Unnamed: 333, 323: Unnamed: 334, 324: Unnamed: 335, 325: Unnamed: 336, 326: Unnamed: 337, 327: Unnamed: 338, 328: Unnamed: 339, 329: Unnamed: 340, 330: Unnamed: 341, 331: Unnamed: 342, 332: Unnamed: 343, 333: Unnamed: 344, 334: Unnamed: 345, 335: Unnamed: 346, 336: Unnamed: 347, 337: Unnamed: 348, 338: Unnamed: 349, 339: Unnamed: 350, 340: Unnamed: 351, 341: Unnamed: 352, 342: Unnamed: 353, 343: Unnamed: 354, 344: Unnamed: 355, 345: Unnamed: 356, 346: Unnamed: 357, 347: Unnamed: 358, 348: Unnamed: 359, 349: Unnamed: 360, 350: Unnamed: 361, 351: Unnamed: 362, 352: Unnamed: 363, 353: Unnamed: 364, 354: Unnamed: 365, 355: Unnamed: 366, 356: Unnamed: 367, 357: Unnamed: 368, 358: Unnamed: 369, 359: Unnamed: 370, 360: Unnamed: 371, 361: Unnamed: 372, 362: Unnamed: 373, 363: Unnamed: 374, 364: Unnamed: 375, 365: Unnamed: 376, 366: Unnamed: 377, 367: Unnamed: 378) have mixed types. Specify dtype option on import or set low_memory=False.
  df_uofl = pd.read_csv(

In [33]:
import os

candidates = ["original-data/baptist.csv", "../original-data/baptist.csv"]
for p in candidates:
    if os.path.exists(p):
        df_baptist = pd.read_csv(p, skiprows=2)
        print(f"Loaded {p} ({df_baptist.shape[0]} rows, {df_baptist.shape[1]} cols)")
        break
else:
    raise FileNotFoundError("baptist.csv not found in any of: " + ", ".join(candidates))

/var/folders/wd/wynvzl4x4sn834srpzwscw_m0000gn/T/ipykernel_99607/2840964108.py:6: DtypeWarning: Columns (0: code|1, 1: code|2|type, 2: code|3, 3: code|3|type, 4: code|4, 5: code|4|type, 6: drug_type_of_measurement) have mixed types. Specify dtype option on import or set low_memory=False.
  df_baptist = pd.read_csv(p, skiprows=2)

Loaded ../original-data/baptist.csv (775240 rows, 28 cols)

In [34]:
import os

candidates = ["original-data/norton.csv", "../original-data/norton.csv"]
for p in candidates:
    if os.path.exists(p):
        df_norton = pd.read_csv(p, skiprows=2)
        print(f"Loaded {p} ({df_norton.shape[0]} rows, {df_norton.shape[1]} cols)")
        break
else:
    raise FileNotFoundError("norton.csv not found in any of: " + ", ".join(candidates))

/var/folders/wd/wynvzl4x4sn834srpzwscw_m0000gn/T/ipykernel_99607/2970755048.py:6: DtypeWarning: Columns (0: standard_charge|negotiated_algorithm, 1: count, 2: additional_payer_notes) have mixed types. Specify dtype option on import or set low_memory=False.
  df_norton = pd.read_csv(p, skiprows=2)

Loaded ../original-data/norton.csv (6383964 rows, 30 cols)

In [31]:
import csv

with open("original-data/baptist.csv", "r", encoding="utf-8", errors="ignore") as f:
    sample = f.read(5000)
    dialect = csv.Sniffer().sniff(sample)

print("Delimiter:", repr(dialect.delimiter))

FileNotFoundError: [Errno 2] No such file or directory: 'original-data/baptist.csv'

In [19]:
with open("original-data/baptist.csv", "r", encoding="utf-8", errors="ignore") as f:
    for i in range(10):
        print(f"Line {i+1}: {repr(f.readline())}")

Line 1: 'hospital_name,last_updated_on,version,location_name,hospital_address,license_number | KY,type_2_npi,"To the best of its knowledge and belief, this hospital has included all applicable standard charge information in accordance with the requirements of 45 CFR 180.50, and the information encoded is true, accurate, and complete as of the date in the file. This hospital has included all payer-specific negotiated charges in dollars that can be expressed as a dollar amount. For payer-specific negotiated charges that cannot be expressed as a dollar amount in the machine-readable file or not knowable in advance, the hospital attests that the payer-specific negotiated charge is based on a contractual algorithm, percentage or formula that precludes the provision of a dollar amount and has provided all necessary information available to the hospital for the public to be able to derive the dollar amount, including, but not limited to, the specific fee schedule or components referenced in such percentage, algorithm or formula.",attester_name\n'
Line 2: 'BAPTIST HEALTH LOUISVILLE HOSPITAL EAST,2026-04-01,3.0.0,BAPTIST HEALTH LOUISVILLE HOSPITAL EAST,4000 Kresge Way Louisville KY 40207,100451,1265539498,true,Richard Carrico\n'
Line 3: 'description,code|1,code|1|type,code|2,code|2|type,code|3,code|3|type,code|4,code|4|type,setting,drug_unit_of_measurement,drug_type_of_measurement,standard_charge|gross,standard_charge|discounted_cash,payer_name,plan_name,modifiers,standard_charge|negotiated_dollar,standard_charge|negotiated_percentage,standard_charge|negotiated_algorithm,median_amount,10th_percentile,90th_percentile,count,standard_charge|min,standard_charge|max,standard_charge|methodology,additional_generic_notes\n'
Line 4: 'HC (72 HR MD OFFICE) DRUG,25010000007,CDM,0250,RC,,,,,outpatient,,,100.00,75.00,AETNA MCR ADV,AETNA MCR ADV,,22.20,22.20,,2.95,0.35,66.86,654,11.00,100.00,percent of total billed charges,One or more instances of the item or service in the 15 months prior to posting the file.\n'
Line 5: 'HC (72 HR MD OFFICE) DRUG,25010000007,CDM,0250,RC,,,,,outpatient,,,100.00,75.00,ANTHEM BLUE ACCESS PPO,ANTHEM BLUE ACCESS PPO,,30.29,30.29,,12.55,1.6,96.86,8823,11.00,100.00,percent of total billed charges,One or more instances of the item or service in the 15 months prior to posting the file.\n'
Line 6: 'HC (72 HR MD OFFICE) DRUG,25010000007,CDM,0250,RC,,,,,outpatient,,,100.00,75.00,ANTHEM BLUE TRAD - ALL OTHER PLANS,ANTHEM BLUE TRAD - ALL OTHER PLANS,,44.25,44.25,,12.55,1.6,96.86,8823,11.00,100.00,percent of total billed charges,One or more instances of the item or service in the 15 months prior to posting the file.\n'
Line 7: 'HC (72 HR MD OFFICE) DRUG,25010000007,CDM,0250,RC,,,,,outpatient,,,100.00,75.00,ANTHEM PATH HMO,ANTHEM PATH HMO,,30.29,30.29,,12.55,1.6,96.86,8823,11.00,100.00,percent of total billed charges,One or more instances of the item or service in the 15 months prior to posting the file.\n'
Line 8: 'HC (72 HR MD OFFICE) DRUG,25010000007,CDM,0250,RC,,,,,outpatient,,,100.00,75.00,ANTHEM PATH HPN,ANTHEM PATH HPN,,27.26,27.26,,12.55,1.6,96.86,8823,11.00,100.00,percent of total billed charges,One or more instances of the item or service in the 15 months prior to posting the file.\n'
Line 9: 'HC (72 HR MD OFFICE) DRUG,25010000007,CDM,0250,RC,,,,,outpatient,,,100.00,75.00,CIGNA - ALL PLANS,CIGNA - ALL PLANS,,23.40,23.40,,2.79,0.398,18.28,375,11.00,100.00,percent of total billed charges,One or more instances of the item or service in the 15 months prior to posting the file.\n'
Line 10: 'HC (72 HR MD OFFICE) DRUG,25010000007,CDM,0250,RC,,,,,outpatient,,,100.00,75.00,HEALTHLINK-ALL PLANS,HEALTHLINK-ALL PLANS,,29.15,29.15,,29.15,,,0,11.00,100.00,percent of total billed charges,There were zero instances of the item or service in the 15 months prior to posting the file\n'

In [21]:
import os

input_file = "../original-data/baptist.csv"
output_file = "baptist_top100.csv"

# Automatically create the 'samplefiles' folder if it doesn't exist
output_dir = os.path.dirname(output_file)
if output_dir and not os.path.exists(output_dir):
    os.makedirs(output_dir)

with open(input_file, "r", encoding="utf-8", errors="ignore") as f_in:
    with open(output_file, "w", encoding="utf-8") as f_out:
        for i in range(100):
            line = f_in.readline()
            if not line:  # Stop if the file has fewer than 100 lines
                break
            f_out.write(line)

print(f"Successfully exported the top 100 rows to {output_file}")

Successfully exported the top 100 rows to samplefiles/baptist_top100.csv

In [23]:
df_baptist = pd.read_csv('baptist_top100.csv', skiprows=2)
df_baptist.head(10)

,description,code|1,code|1|type,code|2,code|2|type,code|3,code|3|type,code|4,code|4|type,setting,...,standard_charge|negotiated_percentage,standard_charge|negotiated_algorithm,median_amount,10th_percentile,90th_percentile,count,standard_charge|min,standard_charge|max,standard_charge|methodology,additional_generic_notes
0,HC (72 HR MD OFFICE) DRUG,25010000007,CDM,250,RC,NaN,NaN,NaN,NaN,outpatient,...,22.20,NaN,2.95,0.350,66.86,654,11.0,100.0,percent of total billed charges,One or more instances of the item or service i...
1,HC (72 HR MD OFFICE) DRUG,25010000007,CDM,250,RC,NaN,NaN,NaN,NaN,outpatient,...,30.29,NaN,12.55,1.600,96.86,8823,11.0,100.0,percent of total billed charges,One or more instances of the item or service i...
2,HC (72 HR MD OFFICE) DRUG,25010000007,CDM,250,RC,NaN,NaN,NaN,NaN,outpatient,...,44.25,NaN,12.55,1.600,96.86,8823,11.0,100.0,percent of total billed charges,One or more instances of the item or service i...
3,HC (72 HR MD OFFICE) DRUG,25010000007,CDM,250,RC,NaN,NaN,NaN,NaN,outpatient,...,30.29,NaN,12.55,1.600,96.86,8823,11.0,100.0,percent of total billed charges,One or more instances of the item or service i...
4,HC (72 HR MD OFFICE) DRUG,25010000007,CDM,250,RC,NaN,NaN,NaN,NaN,outpatient,...,27.26,NaN,12.55,1.600,96.86,8823,11.0,100.0,percent of total billed charges,One or more instances of the item or service i...
5,HC (72 HR MD OFFICE) DRUG,25010000007,CDM,250,RC,NaN,NaN,NaN,NaN,outpatient,...,23.40,NaN,2.79,0.398,18.28,375,11.0,100.0,percent of total billed charges,One or more instances of the item or service i...
6,HC (72 HR MD OFFICE) DRUG,25010000007,CDM,250,RC,NaN,NaN,NaN,NaN,outpatient,...,29.15,NaN,29.15,NaN,NaN,0,11.0,100.0,percent of total billed charges,There were zero instances of the item or servi...
7,HC (72 HR MD OFFICE) DRUG,25010000007,CDM,250,RC,NaN,NaN,NaN,NaN,outpatient,...,39.58,NaN,17.50,3.700,231.00,669,11.0,100.0,percent of total billed charges,One or more instances of the item or service i...
8,HC (72 HR MD OFFICE) DRUG,25010000007,CDM,250,RC,NaN,NaN,NaN,NaN,outpatient,...,85.00,NaN,85.00,NaN,NaN,0,11.0,100.0,percent of total billed charges,There were zero instances of the item or servi...
9,HC (72 HR MD OFFICE) DRUG,25010000007,CDM,250,RC,NaN,NaN,NaN,NaN,outpatient,...,70.00,NaN,70.00,NaN,NaN,0,11.0,100.0,percent of total billed charges,There were zero instances of the item or servi...

In [25]:
import os

input_file = "../original-data/uofl.csv"
output_file = "uofl_top100.csv"

# Automatically create the 'samplefiles' folder if it doesn't exist
output_dir = os.path.dirname(output_file)
if output_dir and not os.path.exists(output_dir):
    os.makedirs(output_dir)

with open(input_file, "r", encoding="utf-8", errors="ignore") as f_in:
    with open(output_file, "w", encoding="utf-8") as f_out:
        for i in range(100):
            line = f_in.readline()
            if not line:  # Stop if the file has fewer than 100 lines
                break
            f_out.write(line)

print(f"Successfully exported the top 100 rows to {output_file}")

Successfully exported the top 100 rows to uofl_top100.csv

In [35]:
import pandas as pd

In [36]:
df_uofl= pd.read_csv('uofl_top100.csv', skiprows=2)

In [37]:
df_uofl

,description,code|1,code|1|type,code|2,code|2|type,code|3,code|3|type,code|4,code|4|type,billing_class,...,additional_payer_notes|WellCare|KY Medicaid,standard_charge|Wellcare|Commercial|negotiated_dollar,standard_charge|Wellcare|Commercial|negotiated_percentage,standard_charge|Wellcare|Commercial|negotiated_algorithm,median_amount|Wellcare|Commercial,10th_percentile|Wellcare|Commercial,90th_percentile|Wellcare|Commercial,count|Wellcare|Commercial,standard_charge|Wellcare|Commercial|methodology,additional_payer_notes|Wellcare|Commercial
0,OB2 PRIVATE,348068255,CDM,NaN,NaN,112,RC,NaN,NaN,facility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,OBSTETRICS- PRIVATE,352070895,CDM,NaN,NaN,112,RC,NaN,NaN,facility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PSYCH PRIVATE,415068305,CDM,NaN,NaN,114,RC,NaN,NaN,facility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8S-HOSPICE,330111061,CDM,NaN,NaN,115,RC,NaN,NaN,facility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8E HOSPICE,300168027,CDM,NaN,NaN,115,RC,NaN,NaN,facility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,STROKE UNIT INTENSIVE CARE,313268092,CDM,NaN,NaN,200,RC,NaN,NaN,facility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,MCU INTENSIVE CARE,341568179,CDM,NaN,NaN,200,RC,NaN,NaN,facility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,8W INTENSIVE CARE,342068194,CDM,NaN,NaN,200,RC,NaN,NaN,facility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,BNU INTENSIVE CARE,345068229,CDM,NaN,NaN,200,RC,NaN,NaN,facility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,EDH INTENSIVE CARE,380668295,CDM,NaN,NaN,200,RC,NaN,NaN,facility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:



df_types = df_uofl.dtypes.reset_index()


df_types.columns = ["Column Name", "Data Type"]


df_types["Data Type"] = df_types["Data Type"].astype(str)

df_types.to_excel("file_data_types.xlsx", index=False)

print("Export completed")

Export complete! Check 'file_data_types.xlsx' in your folder.

In [41]:
import pandas as pd

In [43]:
df_filtered = pd.read_csv('../clean-data/filtered_data.csv')
df_filtered.head()

,hospital,cpt_code,code_type,procedure_name,description,gross_charge,cash_price,negotiated_rate,min_negotiated,max_negotiated,payer_name,plan_name,rate_exceeds_gross
0,BAPTIST HEALTH LOUISVILLE HOSPITAL EAST,193,NaN,SIMPLE PNEUMONIA AND PLEURISY WITH MCC,SIMPLE PNEUMONIA AND PLEURISY WITH MCC,42118.83,31589.12,8841.68,7088.99,42118.83,WELLCARE MCR ADV - ALL OTHER PLANS,WELLCARE MCR ADV - ALL OTHER PLANS,No
1,BAPTIST HEALTH LOUISVILLE HOSPITAL EAST,193,NaN,SIMPLE PNEUMONIA AND PLEURISY WITH MCC,SIMPLE PNEUMONIA AND PLEURISY WITH MCC,42118.83,31589.12,13144.00,7088.99,42118.83,SIHO EXCLUS NTWRK,SIHO EXCLUS NTWRK,No
2,BAPTIST HEALTH LOUISVILLE HOSPITAL EAST,193,NaN,SIMPLE PNEUMONIA AND PLEURISY WITH MCC,SIMPLE PNEUMONIA AND PLEURISY WITH MCC,42118.83,31589.12,8148.26,7088.99,42118.83,HUMANA MCAID,HUMANA MCAID,No
3,BAPTIST HEALTH LOUISVILLE HOSPITAL EAST,193,NaN,SIMPLE PNEUMONIA AND PLEURISY WITH MCC,SIMPLE PNEUMONIA AND PLEURISY WITH MCC,42118.83,31589.12,25335.06,7088.99,42118.83,ANTHEM BLUE TRAD - ALL OTHER PLANS,ANTHEM BLUE TRAD - ALL OTHER PLANS,No
4,BAPTIST HEALTH LOUISVILLE HOSPITAL EAST,193,NaN,SIMPLE PNEUMONIA AND PLEURISY WITH MCC,SIMPLE PNEUMONIA AND PLEURISY WITH MCC,42118.83,31589.12,20767.52,7088.99,42118.83,ANTHEM BLUE ACCESS PPO,ANTHEM BLUE ACCESS PPO,No

In [44]:
df_filtered['code_type'].unique()

array([nan])